language: php

php:
  - '5.6'

git:
  depth: 1

dist: trusty
sudo: required

addons:
  apt:
    packages:
      # install mysql 5.6
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
  hosts:
    - money-tracker.jdenoc.dev

env:
  - APP_DEBUG=false APP_URL=http://money-tracker.jdenoc.dev DB_CONNECTION=mysql DB_DATABASE=money_tracker_test DB_HOST=127.0.0.1 DB_PORT=3306 DB_USERNAME=root DB_PASSWORD=

services:
  - mysql

install:
  - composer install

before_script:
  - mysql -e "CREATE DATABASE money_tracker_test;"

script: vendor/bin/phpunit --coverage-text

after_script:
  - mysql -e "DROP DATABASE money_tracker_test;"