language: generic

git:
  depth: 1

# trusty instance & sudo are needed so we can utilise docker
dist: trusty
sudo: required

addons:
  apt:
    update: true
  hosts:
    - money-tracker.docker

services:
  - docker

env: DOCKER_HOST_IP=host.docker.internal

before_install:
  - docker pull composer/composer:php5-alpine
  - docker-compose -f docker/docker-compose.yml pull
  - docker-compose -f docker/docker-compose.yml build

install:
  # composer install
  - docker container run --rm -t --volume $PWD:/app composer/composer:php5-alpine install
  # start docker containers
  - docker-compose -f docker/docker-compose.yml up -d
  - docker container ls
  - docker volume ls
  # install travis-ci/discord integration script
  - wget https://raw.githubusercontent.com/jdenoc/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh

before_script:
  - docker container exec -t app.money-tracker artisan travis-ci --display-env
#  - docker container exec -t mysql.money-tracker mysql -uroot -e "SHOW DATABASES;"

script:
  - docker container exec -t app.money-tracker vendor/bin/phpunit --testsuite api
  - docker container exec -t app.money-tracker vendor/bin/phpunit --testsuite console
  - docker container exec -t app.money-tracker vendor/bin/phpunit --testsuite web
  - docker container exec -t app.money-tracker vendor/bin/phpunit --testsuite unit

# $WEBHOOK_URL should be set in travis-ci settings
after_success:
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - ./send.sh failure $WEBHOOK_URL

after_script:
  - docker-compose -f docker/docker-compose.yml down -v
  - docker container ls
  - docker volume ls

# make sure ONLY updates to the master & develop branches cause a build
branches:
  only:
    - master
    - develop