language: php

php:
  - '5.6'

git:
  depth: 1

addons:
  hosts:
    - money-tracker.jdenoc.dev

env:
  - APP_DEBUG=false APP_URL=http://money-tracker.jdenoc.dev DB_CONNECTION=mysql DB_DATABASE=money_tracker_test DB_HOST=127.0.0.1 DB_PORT=3306 DB_USERNAME=root DB_PASSWORD=

services:
  - mysql

before_install:
  - apt-get update
  - apt-get install apache2 libapahce2-mod-fastcgi
  # enable php-fpm
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - a2enmod rewrite actions fastcgi alias
  - "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - service apache2 restart
  # disabled xDebug
  - phpenv config-rm xdebug.ini

install:
  - composer install

before_script:
  - mysql -e "CREATE DATABASE money_tracker_test;"

script: phpunit --configuration phpunit.xml --coverage-text

after_script:
  - mysql -e "DROP DATABASE money_tracker_test;"