language: php

php:
  - '5.6'

git:
  depth: 1

addons:
  hosts:
    - money-tracker.jdenoc.dev

env:
  - APP_DEBUG=false APP_URL=http://money-tracker.jdenoc.dev DB_CONNECTION=mysql DB_DATABASE=money_tracker_test DB_HOST=127.0.0.1 DB_PORT=3306 DB_USERNAME=root DB_PASSWORD=

services:
  - mysql

before_install:
  # disabled xDebug
  - phpenv config-rm xdebug.ini
  # show mysql version
  - mysql --version

install:
  - composer install

before_script:
  - mysql -e "CREATE DATABASE money_tracker_test;"

script: vendor/bin/phpunit --coverage-text

after_script:
  - mysql -e "DROP DATABASE money_tracker_test;"