language: php

php:
  - '5.6'

git:
  depth: 1

# trusty instance & sudo are needed so we can utilise docker
dist: trusty
sudo: required

addons:
  hosts:
    - money-tracker.travis

services:
  - docker

before_install:
  - docker pull composer/composer:php5-alpine
  - docker-compose -f docker/docker-compose.travis.yml pull

install:
  # composer install
  - docker container run --rm -t --volume $PWD:/app composer/composer:php5-alpine install
  # start docker containers
  - docker-compose -f docker/docker-compose.travis.yml up -d
  # install travis-ci/discord integration script
  - wget https://raw.githubusercontent.com/jdenoc/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh

before_script:
  - docker container exec -t app.money-tracker artisan travis-ci --display-env
  - docker container exec -t mysql.money-tracker mysql -u root -e "SHOW DATABASES;"
  - docker container ls

script: docker container exec -t app.money-tracker vendor/bin/phpunit --coverage-text

# $WEBHOOK_URL should be set in travis-ci settings
after_success:
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - ./send.sh failure $WEBHOOK_URL

after_script:
  - docker-compose -f docker/docker-compose.travis.yml down -v
  - docker container ls

# make sure ONLY updates to the master & develop branches cause a build
branches:
  only:
    - master
    - develop