version: '3'

services:
  application:
    build:
      context: .
      dockerfile: .docker/app.dockerfile
      args:
        - DISABLE_XDEBUG=${DISABLE_XDEBUG:-false}
    container_name: "app.money-tracker"
    hostname: app.money-tracker
    ports:
      - "80:80"
      - "9003:9003"   # for xdebug
    volumes:
      - .:/var/www/money-tracker
      - ./.docker/logs/application:/var/log/php  # for logs
    environment:
      - APP_ENV=docker
    depends_on:
      - database
      - cache
    dns_search:
      - money-tracker.docker
    networks:
      - net.money-tracker

  database:
    build:
      context: .
      dockerfile: .docker/mysql.dockerfile
    container_name: "mysql.money-tracker"
    hostname: mysql.money-tracker
    volumes:
      - db.money-tracker:/var/lib/mysql
      - ./.docker/logs/database:/var/log/mysql  # for logs
    environment:
      # if you change any of these, be sure to change the corresponding values in .env.docker
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=money_tracker
      - MYSQL_USER=jdenoc
      - MYSQL_PASSWORD=password
    networks:
      - net.money-tracker

  cache:
    build:
      context: .
      dockerfile: .docker/memcached.dockerfile
    container_name: "memcached.money-tracker"
    hostname: memcached.money-tracker
    networks:
      - net.money-tracker

  selenium: # needed for e2e (End-to-End) testing
    build:
      context: .
      dockerfile: .docker/selenium.dockerfile
    container_name: "selenium.money-tracker"
    hostname: selenium.money-tracker
    shm_size: "2g"
    ports:
      - "7900:7900"   # for VNC via browser
    volumes:
      - ./storage/tests/downloads:/home/seluser/Downloads
    environment:
      - VNC_NO_PASSWORD=1
    depends_on:
      - application
    links:
      - application:money-tracker.docker
    networks:
      - net.money-tracker

volumes:
  db.money-tracker: {}

networks:
  net.money-tracker: {}