---
services:
  application:
    build:
      context: .
      dockerfile: .docker/app.dockerfile
      args:
        - DISABLE_XDEBUG=${DISABLE_XDEBUG:-false}
    hostname: app.money-tracker
    ports:
      - "80:80"
      - "9003:9003"   # for xdebug
    volumes:
      - .:/var/www/money-tracker
      - ./.docker/logs/application:/var/log/php  # for logs
    environment:
      - APP_ENV=docker
    depends_on:
      - database
      - cache
    dns_search:
      - money-tracker.test
    networks:
      - default

  database:
    image: mysql:8.0.27
    volumes:
      - db:/var/lib/mysql
      # allows stored function creators to be trusted not to create stored functions that may cause unsafe events to be written to the binary log
      - .docker/conf/mysql-log_bin_trust.cnf:/etc/mysql/conf.d/log_bin_trust.cnf:ro
      # logging
      - .docker/conf/mysql-logging.cnf:/etc/mysql/conf.d/logging.cnf:ro
      - .docker/logs/database:/var/log/mysql
      # health-check
      - .docker/healthcheck/mysql-health-check.sh:/usr/local/bin/mysql-health-check:ro
    environment:
      # if you change any of these, be sure to change the corresponding values in .env.docker
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=money_tracker
      - MYSQL_USER=jdenoc
      - MYSQL_PASSWORD=password
    healthcheck:
      test: mysql-health-check
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - default

  cache:
    image: memcached:1.6.29-alpine
    volumes:
      - .docker/healthcheck/memcached-health-check.sh:/usr/local/bin/memcached-health-check:ro
    healthcheck:
      test: memcached-health-check
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - default

  selenium: # needed for e2e (End-to-End) testing
    image: selenium/standalone-chrome:4.9.0
    shm_size: "2g"
    ports:
      - "7900:7900"   # for VNC via browser
    volumes:
      - storage/tests/downloads:/home/seluser/Downloads
      - .docker/healthcheck/selenium-health-check.sh:/home/seluser/selenium-health-check:ro
    environment:
      - VNC_NO_PASSWORD=1
    healthcheck:
      test: /home/seluser/selenium-health-check
      timeout: 10s
      retries: 3
    depends_on:
      - application
    links:
      - application:money-tracker.test
    networks:
      - default

volumes:
  db:
    name: money-tracker.db

networks:
  default: {}