---
services:
  application:
    build:
      context: .
      dockerfile: .docker/app.dockerfile
      args:
        - DISABLE_XDEBUG=${DISABLE_XDEBUG:-false}
    container_name: "money-tracker.app"
    hostname: app.money-tracker
    ports:
      - "80:80"
      - "9003:9003"   # for xdebug
    volumes:
      - .:/var/www/money-tracker
      - ./.docker/logs/application:/var/log/php  # for logs
    environment:
      - APP_ENV=docker
    depends_on:
      - database
      - cache
    dns_search:
      - money-tracker.test
    networks:
      - default

  database:
    container_name: "money-tracker.mysql"
    environment:
      # if you change any of these, be sure to change the corresponding values in .env.docker
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=money_tracker
      - MYSQL_USER=jdenoc
      - MYSQL_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysql-health-check"]
      interval: 5s
      timeout: 10s
      retries: 10
    hostname: mysql.money-tracker
    image: mysql:8.0.27
    networks:
      - default
    volumes:
      - db:/var/lib/mysql
      - .docker/conf/mysql-log_bin_trust.cnf:/etc/mysql/conf.d/log_bin_trust.cnf
      # healthcheck
      - .docker/healthcheck/mysql-health-check.sh:/usr/local/bin/mysql-health-check
      # logging
      - .docker/conf/mysql-logging.cnf:/etc/mysql/conf.d/logging.cnf
      - .docker/logs/database:/var/log/mysql

  cache:
    build:
      context: .
      dockerfile: .docker/memcached.dockerfile
    container_name: "money-tracker.memcached"
    hostname: memcached.money-tracker
    networks:
      - default

volumes:
  db:
    name: money-tracker.db

networks:
  default: {}
