# .github/actions/app-init/action.yml
name: App Init
description: Initialise app for use
runs:
  using: composite
  steps:
    # re-load docker images
    - run: |
        docker load < .docker/images/application.tar.gz
        docker load < .docker/images/database.tar.gz
        docker load < .docker/images/selenium.tar.gz
        docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME up -d
        docker container exec -t mysql.money-tracker iterate-mysql-health-check
      shell: bash
    # make sure user `www-data` has ownership of everything
    - run: docker container exec -t app.money-tracker chown -R www-data:www-data .
      shell: bash
    # general application setup
    - run: |
        .docker/cmd/artisan.sh cache:clear
        .docker/cmd/artisan.sh view:clear
        .docker/cmd/artisan.sh key:generate
        .docker/cmd/artisan.sh app:version `git describe --always`
        .docker/cmd/artisan.sh config:clear
        docker container exec -t app.money-tracker env
      shell: bash
    # setup laravel log files
    - run: |
        docker container exec -t --user www-data app.money-tracker touch storage/logs/php_error.log
        docker container exec -t --user www-data app.money-tracker touch storage/logs/laravel.log
      shell: bash