# .github/actions/app-init/action.yml
name: App Init
description: Initialise app for use
inputs:
  docker-image-directory:
    description: "Directory docker image(s) were cached/saved"
    required: true
  is-cacheless:
    description: "Set to true to clear cache and create an alternative .env file"
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    # re-load docker images
    - run: |
        for image_name in $(ls ${{ inputs.docker-image-directory }}/${PROJECT_NAME}*.tar.gz)
        do
          docker load -i $image_name
        done
        docker image ls "$PROJECT_NAME*" --no-trunc
      shell: bash
    # start containers
    - run: |
        docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME up -d --force-recreate
        
        i=0
        while [[ $(docker container ls --filter "status=running" -q) != $(docker container ls --filter "status=running" --filter "health=healthy" -q) ]]
        do
          sleep 1
          i=$((i+1))
        done
        echo "it took $i seconds for containers to become healthy"
        
        docker container ls --size --no-trunc
      shell: bash
    # ensure correct user:group ownership
    - run: |
        docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME exec -T --user root application chown -R www-data .
        docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME exec -T --user root selenium chgrp seluser /home/seluser/Downloads
        docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME exec -T --user root selenium chmod g+w /home/seluser/Downloads
      shell: bash
    # general application setup
    - run: |
        .docker/cmd/artisan.sh optimize:clear
        .docker/cmd/artisan.sh key:generate
        .docker/cmd/artisan.sh app:version $(git describe --always)
        .docker/cmd/artisan.sh optimize
        .docker/cmd/artisan.sh view:cache
      shell: bash
    # setup laravel log files
    - run: |
        docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME exec -T --user www-data application touch storage/logs/php_error.log
        docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME exec -T --user www-data application touch storage/logs/laravel.log
      shell: bash
    # clear cache and create alternative .env file
    - if: ${{ inputs.is-cacheless != 'false' }}
      run: |
        .docker/cmd/artisan.sh config:clear
        docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME exec -T --user www-data application cp .env.docker .env.testing
      shell: bash
