# .github/actions/app-init/action.yml
---
name: App Init
description: Initialise app for use
inputs:
  docker-image-directory:
    description: "Directory docker image(s) were cached/saved"
    required: true
runs:
  using: composite
  steps:
    - name: re-load docker images
      run: |
        for image_name in $(ls ${{ inputs.docker-image-directory }}/*.tar.gz)
        do
          docker load -i $image_name
        done
        docker image ls "$(basename $PWD)*"
      shell: bash

    - name: set initial user:group ownership
      run: |
        docker compose \
          run --rm -T --no-deps --user root \
          application \
          chown -R www-data:www-data .
      shell: bash

    - name: create laravel logs
      run: |
        docker compose run --rm --no-deps -T --user www-data application touch /var/log/php/laravel.log
        docker compose run --rm --no-deps -T --user www-data application ln -fs /var/log/php/laravel.log storage/logs/laravel.log
      shell: bash

    - name: ensure correct user:group ownership for other containers
      run: |
        docker compose run --rm --no-deps -T --user root database chgrp root /var/log/mysql
        docker compose run --rm --no-deps -T --user root selenium chgrp seluser /home/seluser/Downloads
        docker compose run --rm --no-deps -T --user root selenium chmod g+w /home/seluser/Downloads
      shell: bash
