version: '3'

services:
  application:
    build:
      context: .. # interpreted as relative to the location of the Compose file
      dockerfile: docker/app.dockerfile
    container_name: "app.money-tracker"
    ports:
      - 80:80
    volumes:
      - ..:/var/www/money-tracker  # .. is interpreted as relative to the location of the Compose file
    environment:
      - PHP_IDE_CONFIG="serverName=money-tracker.docker"
      - APP_ENV=docker
    extra_hosts:
      - dockerhost:$DOCKER_HOST_IP
    dns_search:
      - money-tracker.docker

  database:
    build:
      context: .. # interpreted as relative to the location of the Compose file
      dockerfile: docker/mysql.dockerfile
    container_name: "mysql.money-tracker"
    volumes:
      - db.money-tracker:/var/lib/mysql
    environment:
      # if you change any of these, be sure to change the corresponding values in .env.docker
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=money_tracker
      - MYSQL_USER=jdenoc
      - MYSQL_PASSWORD=password

  selenium: # needed for e2e (End-to-End) testing
    image: selenium/standalone-chrome:latest
    container_name: "selenium.money-tracker"
    links:
    - application:money-tracker.docker
    volumes:
    - /dev/shm:/dev/shm

volumes:
  db.money-tracker: