# .github/actions/setup-composer/action.yml
name: Composer Setup
description: Load composer dependancies
inputs:
  github-token:
    description: 'Github oAuth token'
    required: true
  php-version:
    description: 'PHP version used by composer'
    required: true
runs:
  using: composite
  steps:
    - id: composer-github-token
      run: .docker/scripts/composer.sh config github-oauth.github.com ${{ inputs.github-token }}
      shell: bash
    - id: composer-php-version
      run: .docker/scripts/composer.sh config platform.php ${{ inputs.php-version }}
      shell: bash
    - id: composer-validate
      run: .docker/scripts/composer.sh validate
      shell: bash
    - id: composer-install
      run: .docker/scripts/composer.sh install --no-interaction --optimize-autoloader --prefer-dist -vvv
      shell: bash