# .github/actions/setup-composer/action.yml
name: Composer Setup
description: Load composer dependancies
inputs:
  github-token:
    description: 'Github oAuth token'
    required: true
runs:
  using: composite
  steps:
#    - id: composer-validate  TODO: re-activate when composer.lock is in repo
#      run: .docker/cmd/composer.sh validate
#      shell: bash
    - id: composer-github-token
      run: .docker/cmd/composer.sh config github-oauth.github.com ${{ inputs.github-token }}
      shell: bash
    - id: composer-install
      run: .docker/cmd/composer.sh install --no-interaction --optimize-autoloader
      shell: bash

branding:
  icon: package
  color: blue