# .github/actions/app-stop/action.yml
name: Down docker containers
description: Down docker containers & volumes
runs:
  using: composite
  steps:
    - run: docker compose --file docker-compose.yml --file .docker/docker-compose.selenium.yml down -v
      shell: bash
