# .github/actions/setup-docker/action.yml
name: Docker Setup
description: build docker containers for use while testing
inputs:
  image-path:
    description: 'Path where docker images are saved'
    required: true
runs:
  using: composite
  steps:
    # build docker
    - run: |
        docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME build --build-arg DISABLE_XDEBUG=true
      shell: bash
    # save docker images
    - run: |
        mkdir -p ${{ inputs.image-path }}
        docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME up -d
        docker save $(docker-compose -f .docker/docker-compose.yml -p moneytracker images -q) | gzip > ${{ inputs.image-path }}/${PROJECT_NAME}.tar.gz
      shell: bash