# .github/actions/setup-docker/action.yml
name: Docker Setup
description: build docker containers for use while testing
inputs:
  image-path:
    description: 'Path where docker images are saved'
    required: true
runs:
  using: composite
  steps:
    # build docker
    - run: |
        DISABLE_XDEBUG=true docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME up -d
        docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME exec -T database iterate-mysql-health-check
        docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME ps --status=running
      shell: bash
    # save docker images
    - run: |
        mkdir -p ${{ inputs.image-path }}
        docker save $(docker container ls --format "{{.Image}}") | gzip > ${{ inputs.image-path }}/${PROJECT_NAME}.tar.gz
      shell: bash