# .github/actions/setup-docker/action.yml
name: Docker Setup
description: build docker containers for use while testing
runs:
  using: composite
  steps:
    - run: DISABLE_XDEBUG=true docker-compose -f .docker/docker-compose.yml -p "moneytracker" up -d
      shell: bash
    - run: docker container exec -t mysql.money-tracker iterate-mysql-health-check
      shell: bash
    - run: docker container ls -a
      shell: bash

branding:
  icon: package
  color: blue