# .github/actions/setup-docker/action.yml
name: Docker Setup
description: build docker containers for use while testing
inputs:
  image-path:
    description: 'Path where docker images are saved'
    required: true
runs:
  using: composite
  steps:
    - name: build docker images
      run: docker-compose build --build-arg DISABLE_XDEBUG=true
      shell: bash

    - name: save docker images
      run: |
        mkdir -p ${{ inputs.image-path }}
        docker-compose images
        
        IFS=$'\n'
        for image_name in $(docker-compose images | tail -n +2 | awk '{print $2}')
        do
          docker save $image_name | gzip > .docker/images/${image_name}.tar.gz
        done
      shell: bash