# .github/actions/setup-docker/action.yml
name: Docker Setup
description: build docker containers for use while testing
inputs:
  image-path:
    description: 'Path where docker images are saved'
    required: true
runs:
  using: composite
  steps:
    - id: composer-image-tag
      run: echo "value=composer-local" >> $GITHUB_OUTPUT
      shell: bash

    - name: build docker images
      run: |
        docker-compose build --build-arg DISABLE_XDEBUG=true
        docker build --file .docker/composer.dockerfile --tag ${{ steps.composer-image-tag.outputs.value }} .
      shell: bash

    - name: save docker images
      run: |
        mkdir -p ${{ inputs.image-path }}
        docker image ls "$(basename $PWD)*" --no-trunc
        docker image ls "${{ steps.composer-image-tag.outputs.value }}" --no-trunc
        
        IFS=$'\n'
        for image_name in $(docker image ls "$(basename $PWD)*" --format '{{.Repository}}')
        do
          docker save $image_name | gzip > ${{ inputs.image-path }}/${image_name}.tar.gz
        done
        docker save ${{ steps.composer-image-tag.outputs.value }} | gzip > ${{ inputs.image-path }}/${{ steps.composer-image-tag.outputs.value }}.tar.gz
      shell: bash