# .github/actions/setup-docker/action.yml
name: Docker Setup
description: build docker containers for use while testing
inputs:
  image-path:
    description: 'Path where docker images are saved'
    required: true
runs:
  using: composite
  steps:
    # build docker
    - run: docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME build --build-arg DISABLE_XDEBUG=true
      shell: bash
    # save docker images
    - run: |
        mkdir -p ${{ inputs.image-path }}
        docker image ls "$PROJECT_NAME*" --no-trunc
        
        IFS=$'\n'
        for image_name in $(docker image ls "$PROJECT_NAME*" --format '{{.Repository}}')
        do
          docker save $image_name | gzip > .docker/images/${image_name}.tar.gz
        done
      shell: bash