# .github/actions/setup-docker/action.yml
name: Docker Setup
description: build docker containers for use while testing
runs:
  using: composite
  steps:
    # pull docker images
    - run: |
        docker pull composer:1.9
        docker pull node:12
        docker-compose -f .docker/docker-compose.yml pull
      shell: bash
    # build docker
    - run: |
        DISABLE_XDEBUG=true docker-compose -f .docker/docker-compose.yml -p $PROJECT_NAME up -d
        docker container exec -t mysql.money-tracker iterate-mysql-health-check
        docker container ls -a
      shell: bash
    # save docker images
    - run: |
        mkdir -p .docker/images
        docker save ${PROJECT_NAME}_application | gzip > .docker/images/application.tar.gz
        docker save ${PROJECT_NAME}_database | gzip > .docker/images/database.tar.gz
        docker save selenium/standalone-chrome:3.141.59-xenon | gzip > .docker/images/selenium.tar.gz
      shell: bash