version: '3'

services:
  application:
    build:
      context: .. # interpreted as relative to the location of the Compose file
      dockerfile: .docker/app.dockerfile
      args:
        - DISABLE_XDEBUG=${DISABLE_XDEBUG:-false}
    container_name: "app.money-tracker"
    hostname: app.money-tracker
    ports:
      - 80:80
    volumes:
      - ..:/var/www/money-tracker  # .. is interpreted as relative to the location of the docker-compose file
    environment:
      - PHP_IDE_CONFIG=serverName=money-tracker.docker
      - APP_ENV=docker
    dns_search:
      - money-tracker.docker
    networks:
      - net.money-tracker

  database:
    build:
      context: .. # interpreted as relative to the location of the Compose file
      dockerfile: .docker/mysql.dockerfile
    container_name: "mysql.money-tracker"
    hostname: mysql.money-tracker
    volumes:
      - db.money-tracker:/var/lib/mysql
    environment:
      # if you change any of these, be sure to change the corresponding values in .env.docker
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=money_tracker
      - MYSQL_USER=jdenoc
      - MYSQL_PASSWORD=password
    networks:
      - net.money-tracker

  selenium: # needed for e2e (End-to-End) testing
    image: selenium/standalone-chrome:4.2.0
    container_name: "selenium.money-tracker"
    hostname: selenium.money-tracker
    shm_size: "2g"
    ports:
      - 5901:5900
    depends_on:
      - application
    links:
      - application:money-tracker.docker
    environment:
      - VNC_NO_PASSWORD=1
    networks:
      - net.money-tracker

volumes:
  db.money-tracker: {}

networks:
  net.money-tracker: {}