<?php

namespace App\Providers;

use Illuminate\Support\Facades\Schema;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider {

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register(){
        if ($this->app->environment() !== 'production') {
            // This still needs to be registered because laravel/dusk is not permitted to be discovered via composer
            $this->app->register(DuskServiceProvider::class);
        }
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot(){
        // restrict string length generated by migrations so that we can continue to use mysql 5.6
        Schema::defaultStringLength(191);
    }
}
