# .github/actions/build-vue/action.yml
name: Build Vue
description: Build vue components
runs:
  using: composite
  steps:
    - name: Build/Compile website
      run: .docker/cmd/npm.sh run-script build-prod
      shell: bash