# .github/workflows/main.yml
name: Money-tracker CI - Create draft release

# Triggers the workflow when a tag is pushed
on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  draft-release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Get tag details
        id: get-tag-details
        run: |
          echo ::set-output name=release::$(git describe --tags)

          # TODO: find something that preserves multiline text
          echo 'JSON_RESPONSE<<EOF' >> $MULTILINE_TEST_ENV
          curl https://httpbin.org/json >> $MULTILINE_TEST_ENV
          echo 'EOF' >> $MULTILINE_TEST_ENV

          echo ::set-output name=message::$(git cat-file -p $(git rev-parse $(git describe --tags)) | tail -n +6)

      - name: Create Draft Release
        id: create-draft-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ${{ steps.get-tag-details.outputs.message }}

            ${{ env.MULTILINE_TEST_ENV }}

            ---
            See [here](https://github.com/jdenoc/money-tracker/blob/${{ steps.get-tag-details.outputs.release }}/README.md#prod-updates) for comprehensive instructions.
          draft: true
          prerelease: true

  notification:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: discord
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ github.token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
