# .github/workflows/draft-release.yml
name: Money-tracker CI - Create draft release

# Triggers the workflow when a tag is pushed
on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  draft-release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - id: set-release-name
        run: echo "RELEASE_NAME=$(git describe --tags)" >> $GITHUB_ENV

      - id: set-release-message
        run: |
          message=$(git tag -l --format='%(contents)' ${{ env.RELEASE_NAME }})
          echo 'RELEASE_MESSAGE<<GIT' >> $GITHUB_ENV
          echo "$message" >> $GITHUB_ENV
          echo 'GIT' >> $GITHUB_ENV

      - id: set-previous-release-name
        run: |
          git fetch --tags
          echo "PREVIOUS_RELEASE_NAME=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))" >> $GITHUB_ENV

      - name: Create Draft Release
        id: create-draft-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ${{ env.RELEASE_MESSAGE }}

            ---

            **Full Changelog**: https://github.com/jdenoc/money-tracker/compare/${{ env.PREVIOUS_RELEASE_NAME }}...${{ env.RELEASE_NAME }}

            ---
            See [here](https://github.com/jdenoc/money-tracker/blob/${{ env.RELEASE_NAME }}/docs/UPDATE-PROD.md) for comprehensive instructions.

            Additional steps:
            * [Step 3.a](https://github.com/jdenoc/money-tracker/blob/${{ env.RELEASE_NAME }}/docs/UPDATE-PROD.md#step-3a-optional) - _.env_
            * [Step 3.b](https://github.com/jdenoc/money-tracker/blob/${{ env.RELEASE_NAME }}/docs/UPDATE-PROD.md#step-3b-optional) - _composer_
            * [Step 3.c](https://github.com/jdenoc/money-tracker/blob/${{ env.RELEASE_NAME }}/docs/UPDATE-PROD.md#step-3c-optional) - _npm_
            * [Step 3.d](https://github.com/jdenoc/money-tracker/blob/${{ env.RELEASE_NAME }}/docs/UPDATE-PROD.md#step-3d-optional) - _migrate_
          draft: true
          prerelease: true

  notification:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: discord
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ github.token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
