# .github/workflows/main.yml
name: Money-tracker CI - Create draft release

# Triggers the workflow when a tag is pushed
on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  draft-release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Get tag name
        id: get-tag-name
        run: echo ::set-output name=name::$(git describe --tags)

      - name: Get tag message
        id: get-tag-message
        run: echo ::set-output name=message::$(git cat-file -p $(git rev-parse $(git describe --tags)) | tail -n +6)

      - name: Create Draft Release
        id: create-draft-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            *steps.get-tag-name.outputs.name:* ${{ steps.get-tag-name.outputs.name }}
            *steps.get-tag-message.outputs.message:* ${{ steps.get-tag-message.outputs.message }}

            *ref:* ${{ github.ref }}

            *event:* ${{ toJson(github.event) }}

            *event.release:* ${{ toJson(github.event.release) }}
            *event.release.commit:* ${{ toJson(github.event.release.commit) }}
            *event.release.commit.message:* ${{ github.event.release.commit.message }}

            *event.head_commit:* ${{ toJson(github.event.head_commit) }}
            *event.head_commit.message:* ${{ github.event.head_commit.message }}

            ---
            See [here](https://github.com/jdenoc/money-tracker/blob/${{ steps.get-tag-name.outputs.name }}/README.md#prod-updates) for comprehensive instructions.
          draft: true
          prerelease: true

  notification:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: discord
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ github.token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
