# .github/workflows/enlightn.yml
name: Money-tracker CI - enlightn

# Controls when the action will run.
on: [pull_request]

env:
  DOCKER_HOST_IP: "127.0.0.1"
  PROJECT_NAME: "moneytracker"

jobs:
  analyse:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # retrieve cache
      - name: Cache Docker images
        id: docker-image-cache
        uses: actions/cache@v2
        with:
          path: .docker/images
          key: cache-docker-${{ hashFiles('.docker/*.dockerfile') }}-${{ hashFiles('.docker/docker-compose.yml') }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: cache-composer-${{ hashFiles('composer.lock') }}

      - name: Cache npm/Yarn packages
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-yarn-${{ hashFiles('yarn.lock') }}

      - name: Cache vue
        id: vue-cache
        uses: actions/cache@v2
        with:
          path: |
            public/vue
            public/mix-manifest.json
          key: cache-vue-${{ hashFiles('resources/*') }}

      - name: install enlightn
        run: |
          .docker/cmd/composer.sh .docker/cmd/composer.sh config platform.php 7.3
          .docker/cmd/composer.sh require enlightn/enlightn --dev
          .docker/cmd/artisan.sh vendor:publish --tag=enlightn

      - name: run enlightn
        run: php artisan enlightn --details

  notification:
    runs-on: ubuntu-latest
    needs:  # make sure the notification is sent AFTER the jobs you want included have completed
      - analyse
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled
    timeout-minutes: 60
    steps:
      - name: discord
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ github.token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
